name: keepalive

on:
  schedule:
    - cron: "0 4 1 * *"  # 04:00 UTC on the 1st of every month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    environment: 177
    steps:
      - uses: actions/checkout@v4

      - name: Push empty commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keepalive heartbeat"
          git push
